### ISSUE TITLE
Question: in theory could I use the javascript library separately? 

### ISSUE THREAD

**Issue by EwanValentine** [gophergala2016/thunderbird#4]
I'm thinking of a scenario whereby a Go application is purely an API, could I somehow use the js component of Thunderbird in a client-side js app? Is this compatible with generic JS websocket libraries as well? 

Cheers!

**Comment by owenthereal** [comment]
Are you talking about using it in Node or on the browser? The Thunderbird JS client is meant to be used on a browser. I'm thinking of adding Node client in the future.

**Comment by EwanValentine** [comment]
For example, if I had a React front-end on a separate server and I wanted to use this websocket library for the Go API, but use a generic websocket library in the React front-end

**Comment by owenthereal** [comment]
> use a generic websocket library in the React front-end

What library is that? Websocket is support [natively on most recent browsers](http://caniuse.com/#feat=websockets). But I could see some libraries try to backport to older browsers.

**Comment by owenthereal** [comment]
And `thunberbird` is using the native browser one: https://github.com/jingweno/thunderbird/blob/master/client/src/connection.js#L18.

**Comment by EwanValentine** [comment]
To be honest the JS component of this library looks so simple and uses standard js websockets, it would be really easy just to copy that in say a React front-end etc. Thanks, that's answered my question. Great library :)
